### ISSUE TITLE
install TODO

### ISSUE THREAD

**Issue by cgwalters** [containers/bootc#42]
- [ ] Implement ppc64le and s390x (needs code from both coreos-assembler and coreos-installer)
- [ ] support installing from SELinux-disabled hosts (needs https://github.com/ostreedev/ostree/issues/2804 )
- [ ] Support overwriting disk we used to boot (systemctl switch-root to container image?)
- [ ] Support basic partition configs (e.g. /var)
- [ ] Related, investigate https://www.freedesktop.org/software/systemd/man/systemd-repart.html - maybe we just limit root size and have users embed repart.d configs?
- [ ] Also support running Ignition from the "install boot"; this would make debugging Ignition - configs dramatically nicer
- [ ] Ensure we lock devices when partitioning https://systemd.io/BLOCK_DEVICE_LOCKING/
- [x] Support config files (e.g. distro default filesystem specified in /usr/lib/bootc/install.cfg)
- [x] Support (or default) to only installing EFI if booted that way, etc.
- [ ] Support systemd-boot
- [ ] Clean up/refactor install code to be more distribution-independent in general
- [ ] Consider merging bootupd in here as e.g. bootc bootloader update or so?
- [ ] Documentation
- [ ] More explicitly test host/target kernel compatibility (e.g. filesystems)

**Comment by cgwalters** [comment]
I think at this point, most of these are already split into separate issues.  The ones that aren't, we can find later.
